using System.Collections.Generic;
using UnityEngine;

namespace RaccoonStep
{
    [DefaultExecutionOrder(21000)]
    [DisallowMultipleComponent]
    public sealed class RaccoonCenterOfMassBalance : MonoBehaviour
    {
        public RaccoonPhysicsRig PhysicsRig;
        public RaccoonAlternatingLegController StepController;
        public RaccoonBoneMap BoneMap;
        public RaccoonStepCharacter Character;


        [Header("Mass model")]
        public bool IncludeAllProxyBodies = true;
        public float AdditionalMass = 0f;
        public Vector3 AdditionalMassLocalOffset;

        [Header("Balance correction")]
        public bool ApplyBalanceCorrection = true;
        public float BalanceGain = 1.6f;
        public float MaxCorrectionSpeed = 0.45f;
        public float MaxCorrectionPerFixedStep = 0.025f;

        [Header("Fall response")]
        public bool EnableFallResponse = true;
        [Tooltip("When false, the initial support-foot COM test will not trigger an automatic fall.")]
        public bool EnableAutomaticBalanceFall = false;
        [Tooltip("Release the proxy rigidbodies and let Unity simulate the actual fall.")]
        public bool UseDynamicPhysicsForFall = false;

        public float FallBalanceDistance = 0.24f;
        [Tooltip("Maximum horizontal support radius while one foot is planted.")]
        public float SingleFootSupportRadius = 0.28f;
        [Tooltip("Maximum horizontal support radius while both feet are planted.")]
        public float DoubleFootSupportRadius = 0.38f;
        [Tooltip("When the two feet are closer than this distance, stability decreases.")]
        public float CloseFeetDistance = 0.18f;
        [Tooltip("Smallest support radius when both feet are almost together.")]
        public float CloseFeetSupportRadius = 0.10f;

        [Tooltip("Body tilt angle that immediately starts the fall timer.")]
        public float FallingTiltAngle = 42f;

        public float NormalFallBalanceDistance = 0.42f;
        public float FallGraceTime = 0.18f;
        public float FallDuration = 0.65f;
        public float FallAngle = 78f;
        public float FallDrop = 0.12f;

        [Header("Hybrid physics fall")]
        [Tooltip("Hand off to physics after the controlled lean reaches this progress.")]
        public bool EnableHybridPhysicsFall = true;
        [Range(0.1f, 0.9f)]
        public float HybridPhysicsStart = 0.65f;
        [Range(0.05f, 1f)]
        public float HybridJointStrength = 0.18f;
        [Range(0.05f, 1f)]
        public float HybridJointDamper = 0.25f;
        public float HybridPhysicsSettleTime = 1.0f;
        [Header("Upper body feedback")]
        public bool ApplyUpperBodyLean = true;
        public float UpperBodyLeanGain = 120f;
        public float MaxUpperBodyLean = 12f;
        [Header("Mouse center of mass")]
        public bool EnableMouseCenterOfMass = true;
        [Tooltip("Maximum local COM offset generated by middle-button dragging.")]
        public float MouseCenterOfMassRange = 0.18f;
        [Tooltip("How strongly the mouse COM offset affects the upper-body lean.")]
        public float MouseCenterOfMassGain = 1.0f;
        public float MouseCenterOfMassSmoothing = 8f;


        public Vector3 CenterOfMassWorld { get; private set; }
        public Vector3 CenterOfMassProjection { get; private set; }
        public Vector3 SupportPointWorld { get; private set; }
        public Vector3 BalanceError { get; private set; }
        public float TotalMass { get; private set; }
        public float BodyTiltAngle { get; private set; }
        public float FeetDistance { get; private set; }
        public float EffectiveSupportRadius { get; private set; }


        public bool IsFalling { get { return _isFalling; } }
        public float FallProgress { get { return _fallProgress; } }


        Rigidbody[] _bodies;
        Transform _hipProxy;
        Transform _leftFootProxy;
        Transform _rightFootProxy;

        Transform[] _upperBodyProxies;
        Rigidbody[] _upperBodyBodies;
        Vector3[] _upperBodyNeutralLocalPositions;
        Quaternion[] _upperBodyNeutralLocalRotations;
        Vector3 _hipNeutralLocalPosition;
        bool _isFalling;
        float _unbalancedTime;
        float _fallProgress;
        bool _fallSettled;
        bool _hybridPhysicsActive;
        float _hybridPhysicsTime;
        Quaternion _fallStartRotation;
        Vector3 _fallStartPosition;
        Vector3 _fallPivotWorld;
        Vector3 _fallAxis;
        Vector3 _mouseDragStart;
        Vector3 _mouseComTargetLocal;
        Vector3 _mouseComCurrentLocal;
        bool _middleDragActive;
        [Header("Static COM fall")]
        public bool EnableManualCenterOfMassFall = true;
        [Tooltip("Horizontal manual COM offset required before the fall timer starts.")]
        public float ManualCenterOfMassFallThreshold = 0.12f;
        [Tooltip("How long the manual COM offset must remain beyond the threshold.")]
        public float ManualCenterOfMassFallDelay = 0.65f;
        float _manualComExceededTime;
        Vector3 _manualFallDirectionWorld;


        void Awake()
        {
            if (PhysicsRig == null) PhysicsRig = GetComponent<RaccoonPhysicsRig>();
            if (StepController == null) StepController = GetComponent<RaccoonAlternatingLegController>();
            if (BoneMap == null) BoneMap = GetComponent<RaccoonBoneMap>();
            if (Character == null) Character = GetComponent<RaccoonStepCharacter>();

        }

        void Start()
        {
            RefreshBodies();
            CacheUpperBodyPose();
        }

        void CacheUpperBodyPose()
        {
            if (BoneMap == null || PhysicsRig == null || PhysicsRig.PhysicsRoot == null)
                return;

            BoneMap.BuildFrom(transform);
            _hipProxy = PhysicsRig.GetProxyFor(BoneMap.hips);
            _leftFootProxy = PhysicsRig.GetProxyFor(BoneMap.leftFoot);
            _rightFootProxy = PhysicsRig.GetProxyFor(BoneMap.rightFoot);

            Transform[] visualBones =
            {
                BoneMap.spine,
                BoneMap.neck,
                BoneMap.head,
                BoneMap.leftUpperArm,
                BoneMap.leftLowerArm,
                BoneMap.leftHand,
                BoneMap.rightUpperArm,
                BoneMap.rightLowerArm,
                BoneMap.rightHand
            };

            List<Transform> proxies = new List<Transform>();
            for (int i = 0; i < visualBones.Length; i++)
            {
                Transform proxy = PhysicsRig.GetProxyFor(visualBones[i]);
                if (proxy != null)
                    proxies.Add(proxy);
            }

            _upperBodyProxies = proxies.ToArray();
            _upperBodyBodies = new Rigidbody[_upperBodyProxies.Length];
            _upperBodyNeutralLocalPositions = new Vector3[_upperBodyProxies.Length];
            _upperBodyNeutralLocalRotations = new Quaternion[_upperBodyProxies.Length];
            for (int i = 0; i < _upperBodyProxies.Length; i++)
            {
                _upperBodyBodies[i] = _upperBodyProxies[i].GetComponent<Rigidbody>();
                _upperBodyNeutralLocalPositions[i] = PhysicsRig.PhysicsRoot.InverseTransformPoint(_upperBodyProxies[i].position);
                _upperBodyNeutralLocalRotations[i] = Quaternion.Inverse(PhysicsRig.PhysicsRoot.rotation) * _upperBodyProxies[i].rotation;
            }
            if (_hipProxy != null)
                _hipNeutralLocalPosition = PhysicsRig.PhysicsRoot.InverseTransformPoint(_hipProxy.position);
        }

        void RefreshBodies()
        {
            if (PhysicsRig != null && PhysicsRig.PhysicsRoot != null)
                _bodies = PhysicsRig.PhysicsRoot.GetComponentsInChildren<Rigidbody>(true);
        }

void FixedUpdate()
        {
            if (_isFalling)
            {
                UpdateFall();
                return;
            }

            if (_bodies == null || _bodies.Length == 0)
                RefreshBodies();
            if (_bodies == null || _bodies.Length == 0)
                return;

            Vector3 weightedPosition = Vector3.zero;
            float mass = 0f;
            for (int i = 0; i < _bodies.Length; i++)
            {
                Rigidbody body = _bodies[i];
                if (body == null || body.mass <= 0f)
                    continue;
                weightedPosition += body.worldCenterOfMass * body.mass;
                mass += body.mass;
            }

            if (AdditionalMass > 0f)
            {
                weightedPosition += transform.TransformPoint(AdditionalMassLocalOffset) * AdditionalMass;
                mass += AdditionalMass;
            }

            if (mass <= 0f)
                return;

            TotalMass = mass;
            CenterOfMassWorld = weightedPosition / mass;
            CenterOfMassProjection = new Vector3(
                CenterOfMassWorld.x, GroundHeight(), CenterOfMassWorld.z);
            BodyTiltAngle = GetBodyTiltAngle();

            if (StepController == null)
            {
                SupportPointWorld = CenterOfMassProjection;
                BalanceError = Vector3.zero;
                _unbalancedTime = 0f;
                return;
            }

            SupportPointWorld = StepController.GetBalanceSupportPoint(CenterOfMassProjection);
            BalanceError = new Vector3(
                SupportPointWorld.x - CenterOfMassProjection.x,
                0f,
                SupportPointWorld.z - CenterOfMassProjection.z);

            
            _mouseComCurrentLocal = Vector3.MoveTowards(
                _mouseComCurrentLocal,
                _mouseComTargetLocal,
                Mathf.Max(0f, MouseCenterOfMassSmoothing) * Time.fixedDeltaTime);
ApplyUpperBodyFeedback();

            if (UpdateManualCenterOfMassFall())
                return;

            float balanceDistance = new Vector2(BalanceError.x, BalanceError.z).magnitude;
            bool precisePlacement = IsPrecisePlacementMode();
            float configuredLimit = precisePlacement
                ? FallBalanceDistance
                : NormalFallBalanceDistance;

            // Clamp the configured threshold to the actual support footprint.
            float supportRadius = GetEffectiveSupportRadius();
            EffectiveSupportRadius = supportRadius;
            float allowedDistance = Mathf.Min(configuredLimit, supportRadius);

            bool balanceExceeded = balanceDistance > allowedDistance;
            bool tiltExceeded = BodyTiltAngle >= FallingTiltAngle;
            if (EnableFallResponse && (tiltExceeded || (EnableAutomaticBalanceFall && balanceExceeded)))
            {
                _unbalancedTime += Time.fixedDeltaTime;
                if (_unbalancedTime >= FallGraceTime)
                {
                    BeginFall();
                    return;
                }
            }
            else
            {
                _unbalancedTime = 0f;
            }

            StepController.MaintainSupportFoot();

            if (!ApplyBalanceCorrection || !StepController.IsSingleSupport)
                return;

            Vector3 correction = BalanceError * BalanceGain * Time.fixedDeltaTime;
            correction = Vector3.ClampMagnitude(
                correction, MaxCorrectionSpeed * Time.fixedDeltaTime);
            correction = Vector3.ClampMagnitude(correction, MaxCorrectionPerFixedStep);
            StepController.ApplyBalanceCorrection(correction);
        }


        float GetBodyTiltAngle()
        {
            float rootTilt = Vector3.Angle(transform.up, Vector3.up);
            float hipTilt = 0f;
            if (_hipProxy != null)
                hipTilt = Vector3.Angle(_hipProxy.up, Vector3.up);
            return Mathf.Max(rootTilt, hipTilt);
        }


        float GetEffectiveSupportRadius()
        {
            if (StepController != null && StepController.IsSingleSupport)
            {
                FeetDistance = 0f;
                return SingleFootSupportRadius;
            }

            if (_leftFootProxy == null || _rightFootProxy == null)
            {
                FeetDistance = 0f;
                return DoubleFootSupportRadius;
            }

            Vector3 left = _leftFootProxy.position;
            Vector3 right = _rightFootProxy.position;
            left.y = 0f;
            right.y = 0f;
            FeetDistance = Vector3.Distance(left, right);

            float closeDistance = Mathf.Max(0.01f, CloseFeetDistance);
            float closeFactor = Mathf.Clamp01(
                (closeDistance - FeetDistance) / closeDistance);
            return Mathf.Lerp(DoubleFootSupportRadius,
                CloseFeetSupportRadius, closeFactor);
        }

void BeginFall()
        {
            if (_isFalling || StepController == null)
                return;

            _isFalling = true;
            _fallProgress = 0f;
            _fallSettled = false;
            _hybridPhysicsActive = false;
            _hybridPhysicsTime = 0f;
            _fallStartRotation = transform.rotation;
            _fallStartPosition = transform.position;
            _fallPivotWorld = SupportPointWorld;
            _fallPivotWorld.y = GroundHeight();
            if ((new Vector2(_fallPivotWorld.x, _fallPivotWorld.z)
                - new Vector2(_fallStartPosition.x, _fallStartPosition.z)).sqrMagnitude < 0.0001f)
            {
                _fallPivotWorld = transform.position;
                _fallPivotWorld.y = GroundHeight();
            }

            Vector3 awayFromSupport = _manualFallDirectionWorld.sqrMagnitude > 0.0001f
                ? _manualFallDirectionWorld
                : -BalanceError;
            awayFromSupport.y = 0f;
            if (awayFromSupport.sqrMagnitude < 0.0001f)
                awayFromSupport = -transform.forward;
            awayFromSupport.Normalize();
            _fallAxis = Vector3.Cross(Vector3.up, awayFromSupport).normalized;

            StepController.enabled = false;
            if (Character != null)
                Character.State = RaccoonStepState.Falling;

            if (PhysicsRig != null)
                PhysicsRig.BeginKinematicFallPose();

            if (UseDynamicPhysicsForFall && PhysicsRig != null)
            {
                PhysicsRig.SetPhysicsActive(true);
                Debug.Log("[RaccoonStep] Balance limit exceeded: released proxy rigidbodies for dynamic fall.", this);
            }
            else
            {
                Debug.Log("[RaccoonStep] Balance limit exceeded: entering hybrid controlled fall.", this);
            }
        }

void UpdateFall()
        {
            // Once the physical handoff starts, let the rigidbodies and the
            // ground contacts resolve the pose naturally. Do not teleport
            // individual bodies or the dynamic root during contact.
            if (_fallSettled)
                return;

            if (_hybridPhysicsActive)
            {
                _hybridPhysicsTime += Time.fixedDeltaTime;
                float settleTime = Mathf.Max(0.1f, HybridPhysicsSettleTime);
                if (_hybridPhysicsTime >= settleTime)
                    _fallSettled = true;
                return;
            }

            _fallProgress = Mathf.Clamp01(_fallProgress
                + Time.fixedDeltaTime / Mathf.Max(0.1f, FallDuration));

            // Legacy full-dynamic mode remains available for comparison.
            if (UseDynamicPhysicsForFall && PhysicsRig != null)
                return;

            float blend = _fallProgress * _fallProgress * (3f - 2f * _fallProgress);
            Quaternion fallRotation = Quaternion.AngleAxis(FallAngle * blend, _fallAxis);
            if (PhysicsRig != null)
            {
                PhysicsRig.MoveKinematicFallPose(
                    _fallPivotWorld,
                    fallRotation,
                    Vector3.down * (FallDrop * blend));
            }

            if (EnableHybridPhysicsFall
                && PhysicsRig != null
                && _fallProgress >= Mathf.Clamp01(HybridPhysicsStart))
            {
                PhysicsRig.BeginHybridFall(HybridJointStrength, HybridJointDamper);
                _hybridPhysicsActive = true;
                _hybridPhysicsTime = 0f;
                return;
            }

            if (_fallProgress >= 1f)
            {
                // If hybrid physics is disabled, still release the proxy rig
                // without applying a dynamic root teleport.
                if (PhysicsRig != null)
                    PhysicsRig.SetPhysicsActive(true);
                _fallSettled = true;
            }
        }

        
void UpdateMouseCenterOfMass()
        {
            if (!EnableMouseCenterOfMass)
            {
                _mouseComTargetLocal = Vector3.zero;
                return;
            }

            // PC balance control: WASD shifts the desired center of mass while
            // the camera's mouse-look remains available for terrain/orientation.
            float x = 0f;
            float z = 0f;
            if (Input.GetKey(KeyCode.A)) x -= 1f;
            if (Input.GetKey(KeyCode.D)) x += 1f;
            if (Input.GetKey(KeyCode.S)) z -= 1f;
            if (Input.GetKey(KeyCode.W)) z += 1f;

            Vector3 input = new Vector3(x, 0f, z);
            if (input.sqrMagnitude > 1f)
                input.Normalize();

            float slow = Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift) ? 0.35f : 1f;
            _mouseComTargetLocal = input * (MouseCenterOfMassRange * slow);
        }

void Update()
        {
            UpdateMouseCenterOfMass();

            if (Input.GetKeyDown(KeyCode.R))
                ResetAfterFall();
        }

void ResetAfterFall()
        {
            _isFalling = false;
            _unbalancedTime = 0f;
            _fallProgress = 0f;
            _fallSettled = false;
            _hybridPhysicsActive = false;
            _hybridPhysicsTime = 0f;
            _manualComExceededTime = 0f;
            _manualFallDirectionWorld = Vector3.zero;
            _mouseComTargetLocal = Vector3.zero;
            _mouseComCurrentLocal = Vector3.zero;

            if (StepController != null)
                StepController.ResetToStandingPose();

            if (PhysicsRig != null)
                PhysicsRig.ResetToInitialPose();

            RestoreNeutralUpperBodyPose();

            if (Character != null)
                Character.State = RaccoonStepState.Stable;
        }

        void RestoreNeutralUpperBodyPose()
        {
            if (PhysicsRig == null || PhysicsRig.PhysicsRoot == null || _upperBodyProxies == null)
                return;

            for (int i = 0; i < _upperBodyProxies.Length; i++)
            {
                _upperBodyProxies[i].localPosition = _upperBodyNeutralLocalPositions[i];
                _upperBodyProxies[i].localRotation = _upperBodyNeutralLocalRotations[i];
            }
        }

void ApplyUpperBodyFeedback()
        {
            if (!ApplyUpperBodyLean || _upperBodyProxies == null
                || _upperBodyProxies.Length == 0 || PhysicsRig == null)
                return;

            Transform root = PhysicsRig.PhysicsRoot;
            Vector3 localError = root.InverseTransformDirection(BalanceError);
            localError.y = 0f;

            // Middle-button dragging adds an intentional COM bias. It affects
            // the upper-body feedback only; it never changes the step target.
            localError += _mouseComCurrentLocal * MouseCenterOfMassGain;
            localError.y = 0f;

            float errorMagnitude = localError.magnitude;
            if (errorMagnitude < 0.0001f)
                return;

            Vector3 direction = localError / errorMagnitude;
            float angle = Mathf.Clamp(
                errorMagnitude * UpperBodyLeanGain, 0f, MaxUpperBodyLean);
            Vector3 rotationAxis = Vector3.Cross(Vector3.up, direction);
            if (rotationAxis.sqrMagnitude < 0.0001f)
                return;

            Quaternion lean = Quaternion.AngleAxis(angle, rotationAxis.normalized);
            for (int i = 0; i < _upperBodyProxies.Length; i++)
            {
                Vector3 offset = _upperBodyNeutralLocalPositions[i] - _hipNeutralLocalPosition;
                Vector3 targetLocalPosition = _hipNeutralLocalPosition + lean * offset;
                Quaternion targetLocalRotation = lean * _upperBodyNeutralLocalRotations[i];
                Rigidbody body = _upperBodyBodies != null && i < _upperBodyBodies.Length
                    ? _upperBodyBodies[i]
                    : null;
                if (body != null)
                {
                    body.MovePosition(root.TransformPoint(targetLocalPosition));
                    body.MoveRotation(root.rotation * targetLocalRotation);
                }
            }
        }

        bool IsPrecisePlacementMode()
        {
            if (StepController == null)
                return false;
            Camera camera = StepController.InputCamera != null ? StepController.InputCamera : Camera.main;
            RaccoonCameraFollow cameraFollow = camera != null
                ? camera.GetComponent<RaccoonCameraFollow>()
                : null;
            return cameraFollow != null && cameraFollow.IsFirstPerson;
        }

        float GroundHeight()
        {
            return StepController != null ? StepController.GroundHeight : transform.position.y;
        }
    

        bool UpdateManualCenterOfMassFall()
        {
            if (!EnableManualCenterOfMassFall || PhysicsRig == null || PhysicsRig.PhysicsRoot == null)
            {
                _manualComExceededTime = 0f;
                _manualFallDirectionWorld = Vector3.zero;
                return false;
            }

            Vector3 localOffset = _mouseComCurrentLocal;
            localOffset.y = 0f;
            float threshold = Mathf.Max(0.001f, ManualCenterOfMassFallThreshold);
            if (localOffset.magnitude < threshold)
            {
                _manualComExceededTime = 0f;
                _manualFallDirectionWorld = Vector3.zero;
                return false;
            }

            _manualComExceededTime += Time.fixedDeltaTime;
            _manualFallDirectionWorld = PhysicsRig.PhysicsRoot.TransformDirection(localOffset.normalized);
            _manualFallDirectionWorld.y = 0f;
            _manualFallDirectionWorld.Normalize();

            if (_manualComExceededTime >= Mathf.Max(0.01f, ManualCenterOfMassFallDelay))
            {
                BeginFall();
                return true;
            }

            return false;
        }
}
}
